Many improvements.

diff --git a/mingw-lite b/mingw-lite
--- a/mingw-lite
+++ b/mingw-lite
@@ -1,36 +1,47 @@
 #!/bin/bash
 
+export PATH=$PATH:/e/dev/mingw64/bin
+
+DIR_TMP=_build
 DIR_TOP=$PWD
 DIR_CFG=$PWD/config
 DIR_SRC=$PWD/source
 DIR_REL=$PWD/release
 DIR_BLD=$DIR_REL/mingw
-DIR_TMP=_build
 DIR_TAG=$DIR_SRC/_tags
 DIR_DEP=$DIR_SRC/_deps
 
 
-ARCH=i686
-HOST=${ARCH}-w64-mingw32
 JOBS=4
+BITS=64
+[[ $BITS == 32 ]] && {
+	STIB=64
+	ARCH=i686
+} || {
+	STIB=32
+	ARCH=x86_64
+}
+HOST=${ARCH}-w64-mingw32
 
+# MSYS's make
+MAKE=/bin/make
 
-GREEN='\e[32m'
-YELLOW='\e[33m'
-WHITE='\e[37m'
-DEFAULT_COLOR='\e[0m'
-CLEAR_REST='\033[0K'	# clears rest of line
+COL_GRN='\e[32m'
+COL_YLW='\e[33m'
+COL_WHT='\e[37m'
+COL_DEF='\e[0m'
+CLR_RST='\033[0K'
 
-timestamp() { echo -ne $YELLOW"[`date +%H:%M:%S`] "; }
+timestamp() { echo -ne $COL_YLW"[`date +%H:%M:%S`] "; }
 
 # prints error message and exits with return code 1
 # $1 - error message
-error() { echo; timestamp; echo -e '\e[31m'$1$DEFAULT_COLOR; exit 1; }
+error() { echo; timestamp; echo -e '\e[31m'$1$COL_DEF; exit 1; }
 
 # $1 - action
 # $2 - message
-status() { echo -ne "\r"; timestamp; echo -ne $WHITE$1 $GREEN$2$DEFAULT_COLOR$CLEAR_REST; }
-result() { echo -ne "\r"; timestamp; echo  -e $WHITE$1 $GREEN$2$CLEAR_REST; }
+status() { echo -ne "\r"; timestamp; echo -ne $COL_WHT$1 $COL_GRN$2$COL_DEF$CLR_RST; }
+result() { echo -ne "\r"; timestamp; echo  -e $COL_WHT$1 $COL_GRN$2$CLR_RST; }
 
 # check for DIR, make it, enter it
 check_make_enter() { [[ ! -d $1 ]] && mkdir $1; cd $1; }
@@ -42,18 +53,27 @@ download() {
 		status $PKG "downloading"
 		local log=$DIR_TOP/${PKG}_download.log
 
-		case $SRC in
-			svn)
-				svn co $URL $DIR_SRC/$PKG > $log 2>&1 ;;
+		case $URL in
+			*cvs*)
+				cd $DIR_SRC
+				cvs -z3 -d $URL co $PKG > $log 2>&1
+				cd ..
+				exit 0;
+				;;
 
-			git)
-				git clone $URL $DIR_SRC/$PKG > $log 2>&1 ;;
+			*svn*)
+				svn co $URL $DIR_SRC/$PKG > $log 2>&1
+				;;
 
-			*)
-				case $SRC in
-					gz) flg=z ;;
-					bz2) flg=j ;;
-					xz|lzma) flg=J ;;
+			*git*)
+				git clone $URL $DIR_SRC/$PKG > $log 2>&1
+				;;
+
+			*tar*)
+				case $URL in
+					*gz*) flg=z ;;
+					*bz2*) flg=j ;;
+					*xz*|*lzma*) flg=J ;;
 				esac
 				wget -O - $URL 2> $log | tar x${flg}f - -C $DIR_SRC > $log 2>&1 && mv $DIR_SRC/${PKG}* $DIR_SRC/$PKG >> $log 2>&1
 				;;
@@ -72,8 +92,11 @@ configure() {
 		local log=$DIR_TOP/${PKG}_configure.log
 
 		check_make_enter $DIR_SRC/$PKG/$DIR_TMP
+
+		[[ ! -f ../configure ]] && { cd ..; autoreconf -i > /dev/null 2>&1; cd $DIR_TMP; }
+
 		../configure --help > _${PKG}-help.txt
-		../configure ${CFG[@]} > $log 2>&1 || error "configure error, see $log (or _${PKG}-help.txt for help)"
+		../configure --host=$HOST --build=$HOST --target=$HOST ${CFG[@]} > $log 2>&1 || error "configure error, see $log (or _${PKG}-help.txt for help)"
 
 		rm -f $log > /dev/null 2>&1
 		touch $tag
@@ -88,7 +111,7 @@ build() {
 		local log=$DIR_TOP/${PKG}_build.log
 
 		cd $DIR_SRC/$PKG/$DIR_TMP
-		make -j$JOBS "CFLAGS=$CFL" > $log 2>&1 || error "make error, see $log"
+		$MAKE -j$JOBS "CFLAGS=$CFL" > $log 2>&1 || error "make error, see $log"
 
 		rm -f $log > /dev/null 2>&1
 		touch $tag
@@ -103,7 +126,7 @@ install() {
 		local log=$DIR_TOP/${PKG}_install.log
 
 		cd $DIR_SRC/$PKG/$DIR_TMP
-		make install-strip > $log 2>&1 || make install > $log 2>&1 || error "install error, see $log"
+		$MAKE install-strip > $log 2>&1 || $MAKE install > $log 2>&1 || error "install error, see $log"
 
 		rm -f $log > /dev/null 2>&1
 		touch $tag
@@ -164,8 +187,6 @@ case $1 in
 			. $pkg
 			CFL="-fomit-frame-pointer $CFL"
 
-			#echo $URL | grep svn
-
 			download
 			configure
 			build
@@ -174,17 +195,17 @@ case $1 in
 		done
 
 		status "MinGW" "postprocessing"
-		[[ -d $DIR_BLD/include ]] && mv $DIR_BLD/include $DIR_BLD/i686-w64-mingw32
-		[[ -d $DIR_BLD/lib/gcc/i686-w64-mingw32/lib ]] && mv $DIR_BLD/lib/gcc/i686-w64-mingw32/lib/* $DIR_BLD/lib && rm -rf $DIR_BLD/lib/gcc/i686-w64-mingw32/lib
-		[[ -d $DIR_BLD/i686-w64-mingw32/bin ]] && rm -rf $DIR_BLD/i686-w64-mingw32/bin
-		[[ -d $DIR_BLD/i686-w64-mingw32/lib ]] && rm -rf $DIR_BLD/i686-w64-mingw32/lib
+		[[ -d $DIR_BLD/include ]] && mv $DIR_BLD/include $DIR_BLD/${ARCH}-w64-mingw32
+		[[ -d $DIR_BLD/lib/gcc/${ARCH}-w64-mingw32/lib ]] && mv $DIR_BLD/lib/gcc/${ARCH}-w64-mingw32/lib/* $DIR_BLD/lib && rm -rf $DIR_BLD/lib/gcc/${ARCH}-w64-mingw32/lib
+		[[ -d $DIR_BLD/${ARCH}-w64-mingw32/bin ]] && rm -rf $DIR_BLD/${ARCH}-w64-mingw32/bin
+		#[[ -d $DIR_BLD/${ARCH}-w64-mingw32/lib ]] && rm -rf $DIR_BLD/${ARCH}-w64-mingw32/lib
 		[[ -d $DIR_BLD/share ]] && rm -rf $DIR_BLD/share
-		rm -f $DIR_BLD/bin/i686-w64-mingw32*.exe
+		rm -f $DIR_BLD/bin/${ARCH}-w64-mingw32*.exe
 
 		status "MinGW" "compress"
 		[[ -d $DIR_BLD ]] && 7za a -mx=9 -md=64m -ms=on -mmt ${0##*/}-4.7.2-$ARCH-`date +%Y%m%d`-`date +%H%M%S`.7z $DIR_BLD > /dev/null 2>&1
 
-		result "MinGW" "ok"
+		result "MinGW" "ready"
 
 		dt=$(($(date +%s) - $TIME_START))
 		ds=$((dt % 60))
